#version: '2'
#services:
#  app:
#    image: 'fintech-payment-api-sqd11b:latest'
#    build:
#      context: .
#    ports:
#      - "8080:8080"
#    container_name: fintechApp
#    depends_on:
#      - fintechDb
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://fintechDb:5432/fintech-app
#      - SPRING_DATASOURCE_USERNAME=postgres
#      - SPRING_DATASOURCE_PASSWORD=1234
#      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
#  fintechDb:
#    image: 'postgres:latest'
#    container_name: fintechDb
#    ports:
#      - "5434:5432"
#    environment:
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=1234